### ISSUE TITLE
ECR image limits

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#44]
The documented limit to the number of images in an ECR repository is 1000. The `ecr:ListImages` request provides no insight into which images are older and which are younger -- in fact there's no clear indication of the sorting order.

How will we manage repository size?

cc @yhahn @emilymdubois @emilymcafee

**Comment by yhahn** [comment]
Per chat, proposal is to add a cleanup routine that:

- Lists ECR images,
- Finds correlated timestamps of commits using the cloned repo, e.g. via `git show <commit>`,
- Cleans up old images

We've got some time to implement this, but probably not a ton before some repo hits 1000 images and then :fire: : )

**Comment by emilymdubois** [comment]
A few questions for ya folks:

* **Missing image tags and commits**: Some ECR images do not have an image tag, and some ECR images reference a commit that is no longer reachable on GitHub (my guess is due to rebasing). Using the GitHub API, we're not able to retrieve information about when these commits were made. At the moment, I'm logging what can't be retrieved and tagging them for deletion. Are there reasons why we would want to hold onto these?
* **Old images**: I imagine we want to consider age as a secondary filter to ECR image count. For example, if `images.length <= n` records, do nothing. If `images.length > n` records, delete the oldest records until `images.length <= n`. Does that sound reasonable, or do we also want to add on an additional expiry age (e.g., all images older than 6 months get 🔪 )?

**Comment by rclark** [comment]
>  Some ECR images do not have an image tag

I'm surprised by this -- they have no tag? <none> or something?

**Comment by yhahn** [comment]
> Missing image tags and commits

Sounds like this might be cruft from early ECS experiments/development. If we can't track down how these came to be might make sense to just clean these up by hand.

From that point on our cleanup script could basically ignore anything that doesn't look like a `GitSha` -- just in case someone's doing something manually or important that shouldn't get blown away.

> Old images

@emilymdubois your logic makes sense to me. Ideally we'd also always preserve non-GitSha tag images -- for the use case where you want to keep a really old commit of a repo running on the side or something we could just say "tag that commit."

**Comment by emilymdubois** [comment]
Closed via [PR #63](https://github.com/mapbox/ecs-conex/pull/63)
